---
version: '3'
services:
    zookeeper-1:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper1
        container_name: zookeeper1
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: "2181"
            ZOOKEEPER_TICK_TIME: "2000"
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
        ports:
            - "2181:2181"

    zookeeper-2:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper2
        container_name: zookeeper2
        environment:
            ZOOKEEPER_SERVER_ID: 2
            ZOOKEEPER_CLIENT_PORT: "2182"
            ZOOKEEPER_TICK_TIME: "2000"
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
        ports:
            - "2182:2182"

    zookeeper-3:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper3
        container_name: zookeeper3
        environment:
            ZOOKEEPER_SERVER_ID: 3
            ZOOKEEPER_CLIENT_PORT: "2183"
            ZOOKEEPER_TICK_TIME: "2000"
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
        ports:
            - "2183:2183"

    kafka-1:
        image: confluentinc/cp-kafka:latest
        hostname: kafka1
        container_name: kafka1
        depends_on:
            - zookeeper-1
            - zookeeper-2
            - zookeeper-3
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            KAFKA_LISTENERS: INTERNAL://kafka1:19091, PLAINTEXT://kafka1:9091
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9091,INTERNAL://kafka1:19091
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        ports:
           - "9091:9091"

    kafka-2:
        image: confluentinc/cp-kafka:latest
        hostname: kafka2
        container_name: kafka2
        depends_on:
            - kafka-1
        environment:
            KAFKA_BROKER_ID: 2
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            KAFKA_LISTENERS: INTERNAL://kafka2:19092, PLAINTEXT://kafka2:9092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9092,INTERNAL://kafka2:19092
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        ports:
           - "9092:9092"

    kafka-3:
        image: confluentinc/cp-kafka:latest
        hostname: kafka3
        container_name: kafka3
        depends_on:
            - kafka-2
        environment:
            KAFKA_BROKER_ID: 3
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            KAFKA_LISTENERS: INTERNAL://kafka3:19093, PLAINTEXT://kafka3:9093
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9093,INTERNAL://kafka3:19093
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
        ports:
           - "9093:9093"

    schema_registry:
        image: confluentinc/cp-schema-registry
        hostname: schema_registry
        depends_on:
            - kafka-3
        ports:
            - "8081:8081"
        environment:
            SCHEMA_REGISTRY_HOST_NAME: schema_registry
            SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL: 'zookeeper1:2181'
            SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka1:9091,PLAINTEXT://kafka2:9092,PLAINTEXT://kafka3:9093


