---
version: '3'
services:
    zookeeper-1:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper1
        container_name: zookeeper1
        environment:
            ZOOKEEPER_SERVER_ID: 1
            ZOOKEEPER_CLIENT_PORT: "2181"
            ZOOKEEPER_TICK_TIME: "2000"
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
        ports:
            - "2181:2181"
        extra_hosts:
            - "moby:127.0.0.1"
            - "localhost: 127.0.0.1"

    zookeeper-2:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper2
        container_name: zookeeper2
        environment:
            ZOOKEEPER_SERVER_ID: 2
            ZOOKEEPER_CLIENT_PORT: "2182"
            ZOOKEEPER_TICK_TIME: "2000"
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
        ports:
            - "2182:2182"
        extra_hosts:
            - "moby:127.0.0.1"
            - "localhost: 127.0.0.1"

    zookeeper-3:
        image: confluentinc/cp-zookeeper:latest
        hostname: zookeeper3
        container_name: zookeeper3
        environment:
            ZOOKEEPER_SERVER_ID: 3
            ZOOKEEPER_CLIENT_PORT: "2183"
            ZOOKEEPER_TICK_TIME: "2000"
            ZOOKEEPER_SERVERS: zookeeper1:2888:3888;zookeeper2:2888:3888;zookeeper3:2888:3888
        ports:
            - "2183:2183"
        extra_hosts:
            - "moby:127.0.0.1"
            - "localhost: 127.0.0.1"

    kafka-1:
        image: confluentinc/cp-kafka:latest
        hostname: kafka1
        container_name: kafka1
        depends_on:
            - zookeeper-1
            - zookeeper-2
            - zookeeper-3
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper1:2181,zookeeper2:2181,zookeeper3:2181
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9091
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        ports:
           - "9091:9091"
        extra_hosts:
            - "moby:127.0.0.1"
            - "localhost: 127.0.0.1"

